apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: statping
  namespace: hello-world
  labels:
    app: statping
    service: statping
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: microk8s-hostpath
