apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-world
  namespace: hello-world
  labels:
    app: hello-world
    service: nginx
  annotations:
    cert-manager.io/issuer: webapps.fr
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: hello-world.webapps.fr
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
  tls:
  - hosts:
    - hello-world.webapps.fr
    secretName: hello-world.webapps.fr-tls
